### ISSUE TITLE
WP_CONTENT_URL should not be used by plugin authors

### ISSUE THREAD

**Issue by matt-bernhardt** [micropackage/filesystem#4]
Hello,
I have been debugging a problem that I've run into with the Notifications plugin, and believe that I have traced the issue to this package, and its use of `WP_CONTENT_URL`.

https://github.com/micropackage/filesystem/blob/develop/src/Filesystem.php#L183

The observed behavior is that the `scripts.js` file cannot load when needed because it is being loaded over http, not https. Other plugins and themes on our network do not run into this problem. As I went through the Notifications codebase, I found this filesystem abstraction, and its use of the internal constant `WP_CONTENT_URL`. When I inspect that constant on our site, I see it reporting an http protocol.

In the course of identifying this, I came across this page in the WordPress codex:
https://codex.wordpress.org/Determining_Plugin_and_Content_Directories

...which includes the note that constants like `WP_CONTENT_URL` should not be used directly by plugins or themes. There is a related function, `content_url()` which returns the correct protocol.

Is it possible to change this method to use `content_url()` rather than the `WP_CONTENT_URL` contant? When I make this change locally, the scripts in Notifications are loaded correctly, and everything appears to work.

Thanks for your consideration...

**Comment by jakubmikita** [comment]
Thank you @matt-bernhardt!

The fix has been patched in the above commit, I'll release the new package version and the new Notification plugin this week.
